<?php

namespace AppBundle\Repository;

/**
 * ReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplyRepository extends \Doctrine\ORM\EntityRepository
{
}
